# Generated by Django 5.1 on 2024-08-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicios', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cronograma', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cronograma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatosBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('horario', models.TextField()),
                ('cantidad_participantes', models.IntegerField()),
                ('instructor', models.TextField()),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_del_curso', models.CharField(blank=True, max_length=20, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('materiales_necesarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('dias', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datos_base',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temario',
                'managed': False,
            },
        ),
    ]
